### ISSUE TITLE
 plotHeatmapH throws error: Error in !pos : invalid argument type

### ISSUE THREAD

**Issue by dvdylus** [fjcamlab/deco#2]
Hi,

When I try to plot my analysis or the given example using the plotHeatmapH function it throws the following error:

Error in !pos : invalid argument type

Please correct me if I am wrong, I see that in the function you use it to mark the positions that have an NA value in order to be not considered for the plotting. At somepoint during the analysis "pos" is becoming an object:

> class(pos)
[1] "standardGeneric"
attr(,"package")
[1] "methods"

And I think this is the reason. I also traced it back to the library(Homo.sapiens) BiocGeneric but am not sure how to fix it best in your code? Any help would be highly appreciate it. Please let me know if you need other information from me!

Cheers,
David

**Comment by fjcamlab** [comment]
Hi @dvdylus,

Thank you for letting me know. 

Yes, "pos" was causing a bug when "plotHeatmapH" tried to generate colours for sample categories. It should work now in the new version on GitHub. Please let me know any other issue!

Cheers,
Francisco

**Comment by marlisese** [comment]
Dear Francisco, 
This issue with the 
> Error in !pos : invalid argument type

seems to happen still, just FYI
Martha

**Comment by josemss** [comment]
The new version of the 'deco' package in Bioconductor works for me.
