### ISSUE TITLE
unbalanced classes bug in decoRDA 

### ISSUE THREAD

**Issue by melinagallopin** [fjcamlab/deco#3]
Dear @fjcamlab ,

I would like to use your package but I came across this issue due to unbalanced design in classes. Here is a minimal example that produces the error: 

```r
data <- matrix(rnorm(12976*355),ncol=355)
classes <- sample(1:2,prob=c(2/3,1/3),355,replace=TRUE)
colnames(data) <- names(classes) <- paste0("sam",1:355)
resDeco <- decoRDA(data=data,classes=classes)
```

I suspect the error comes from the factorial [here](https://github.com/fjcamlab/deco/blob/3a9226615918751a2d1c6b2ca8c6d7a885bee4cc/R/additionalFunctions.R#L487).

Thank you for you package. I am looking forward to try it. 

Mélina

**Comment by fjcamlab** [comment]
Hi @melinagallopin  ,

Thanks for letting me know. 
I amended the calculation of factorials, so datasets with big number of samples per class will have a limit of `1e9` iterations if `iterations==0` is defined by user. Otherwise, `iterations` will define the maximum.

Let me know anything else,
Francisco

**Comment by melinagallopin** [comment]
Hi @fjcamlab, 

Thank you for replying so rapidly. The function is working now on my data 👍 .

By the way, I discuss this problem with a friend and he told me that the `choose` function from R was more robust than `factorial` : 

``` r
## Small example
r <- 10
n1 <- 150
n2 <- 100
# choose and factorials give the same result
all.equal(prod(factorial(c(n1, n2)) / (factorial(r) * factorial(c(n1, n2) - r))),
          prod(choose(c(n1, n2), r)))
# and choose is faster
microbenchmark::microbenchmark(prod(factorial(c(n1, n2)) / (factorial(r) * factorial(c(n1, n2) - r))),
                               prod(choose(c(n1, n2), r)))

## Larger example
r <- 10
n1 <- 200
n2 <- 100
# factorial gives NaN
prod(factorial(c(n1, n2)) / (factorial(r) * factorial(c(n1, n2) - r)))
# But choose still gives a result
prod(choose(c(n1, n2), r))

## choose can cope with big numbers
r <- 10
n1 <- 10000
n2 <- 10000
# factorial gives NaN
prod(factorial(c(n1, n2)) / (factorial(r) * factorial(c(n1, n2) - r)))
# But choose still gives a result
prod(choose(c(n1, n2), r))
```

I don't if it will be useful for you since it gives large number. But I thought it would be nice to mention it to you.

Mélina

**Comment by fjcamlab** [comment]
Hi @melinagallopin ,
Thank you for the suggestion, it works faster. I will change the code.
Francisco
