### ISSUE TITLE
double error: "Error in !pos : invalid argument type" and "Error in message(msg) : object 'msg' not found"

### ISSUE THREAD

**Issue by Pisto94** [fjcamlab/deco#5]
Greetings.

I have found two different issues when I tried to run this code with different objects in R, and unluckily probably are the same of the 2 precedent issues I read.
In particular, using default "ALCLdata" object, there're 2 error messages in the final part of the code:

1) The first one is about running plotHeatmapH function, and it seems to be referred about the non coding of pos. Opening the function, "pos" is not defined before the funcion itself.

"Error in !pos : invalid argument type" 

2) The second one instead is about the function "decoReport", used to obtain results. 

"Error in message(msg) : object 'msg' not found"

Is it possible to fix these issues in order to use and obtain correct results? 

Thanks in advice

**Comment by josemss** [comment]
The new version of the 'deco' package in Bioconductor works for me.
